### PR TITLE
add button to decrement prosperity

### PR DESCRIPTION
**Pull request by signed**

### CODE REVIEW

**Comment by kosta** [comment]
I like the code changes in general.

Some criticism:
* In general, please ping me about changes you want to do at least before you start so that we don't duplicate work. 
  * My plan for tonight would be to add an "Add Items" button in the "add cards" modal, so that we can finally add single items to the item list. (And not just draw random items)
  * Related to that, I might try to make the "Add Cards" UI non-modal, so that it can be used _while_ e.g. in a "Road Event" modal dialogue. However, before we do this, we need to check how shuffling a stack and Road/City Events interact (and in which order this works).
  * Feel free to pick either of these two items if you want. I would be ok to not write code tonight :)

* I don't like the "minus" button in front of "Prosperity". In the rules, Prosperity can never decrease, so you only need this if you misclicked. I'd prefer to have an "are you sure to increase prosperity to n?" Dialog if you insist (but was too lazy to implement it). But I'd be ok with "just edit the json if you need to decrease prosperity" :)

* Instead of the drop-down what about just always listing all items like this? (In other words, adding an `<h3>` for each prosperity level)

```js
rangeFrom(1, prosperity).map(|p| => 
  <div>
    <h3>Prosperity {p}</h3>
    {itemsAtLevel(p)}
  </div>
```

**Comment by signed** [comment]
> But I'd be ok with "just edit the json if you need to decrease prosperity"

Works for me. I do not like the 'Are you really really sure' buttons in general. I prefer to have an easy undo -> minus button

> Instead of the drop-down what about just always listing all items like this

After a prosperity increase I'm usually interested to only see the new items preferably without having to scroll. Regardless of the drop down, adding the `<h3>` makes sense.

I'm not a 100%  fit today, will try to update the pull request but will probably not make other changes today. More code for you :)

**Comment by signed** [comment]
Updates are done. Adjust as you see fit.

**Comment by kosta** [comment]
This is perfect! 👍 

> I do not like the 'Are you really really sure' buttons in general.

I agree.

**Pull request merged**
