### PR TITLE
draw random battle goals for the entire party

### PR DESCRIPTION
**Pull request by signed**

### CODE REVIEW

**Comment by kosta** [comment]
I'm not a huge fan of the `drawDistinctBattleGoals` implementation. It could run into an infinite loop if count > array length and will get slower the more cards you draw. I would prefer if you could fill an array, shuffle it and slice the first n cards. 

Currently, these are just number, which is fine for us and for now. However, I'd love to make this generally suitable. But for that, we'd need a settings dialog. And maybe only reveal one players battle goal at a time etc. Consider these feature requests :)

**Comment by signed** [comment]
Can you please post the link to the community battle goals you found?

**Comment by kosta** [comment]
Unfortunately, they were only sent to me by email and I'm not sure whether we're allowed to publish them. I'll ask for permission. I can send them by email in the meantime but please don't publish in the repo.

**Comment by kosta** [comment]
Looks good!

**Pull request merged**
