### PR TITLE
Jest and Enzyme setup

### PR DESCRIPTION
**Pull request by signed**

### CODE REVIEW

**Comment by signed** [comment]
should be merged after #20

**Comment by kosta** [comment]
The tests look pretty cool, but I must say we're entering JavaScript config hell.

**Comment by signed** [comment]
I agree, there are a lot of configuration files.
There are a bunch of helper scripts around that hide a lot of the configuration behind conventions.
But for learning purposes I prefer to do it the hard way :)

**Comment by kosta** [comment]
Yeah more magic scripts don't necessarily don't make it better :)

**Pull request merged**
