### PR TITLE
Webpack

### PR DESCRIPTION
**Pull request by signed**
This requires a build step now before we can run it.
We need to adjust the deployment.
How do you do the deployment right now?

### CODE REVIEW

**Comment by kosta** [comment]
I now remember why I wanted to avoid this :) But yeah the size of this project demands to split up sourcefiles so we need something like webpack etc...

I'm happy to merge this, BUT: If we move to TypeScript, how would the setup look? Is it different, e.g. would be use the ts compiler instead of babel? I'd prefer to move to typescript anyway, but I'm not 100% of the effort involved. See https://www.typescriptlang.org/docs/handbook/react-&-webpack.html 

Feel free to ignore this if it makes more sense to you to first move to webpack and then to TypeScript later, if ever.

**Comment by kosta** [comment]
Also, please "publish" the webpack artifacts to `docs/` directory so that github pages can be configures to serve that subdir. Idea would be to only update `docs/` in master branch (to avoid merge conflicts), but do this after each merge.

**Comment by kosta** [comment]
Also, please "publish" the webpack artifacts to `docs/` directory so that github pages can be configures to serve that subdir. Idea would be to only update `docs/` in master branch (to avoid merge conflicts), but do this after each merge. Sounds good?

**Comment by signed** [comment]
> If we move to TypeScript, how would the setup look

I tried to make TypeScript work on top of this setup yesterday, but failed because of the babel-webpack-typescript mix I was not able to get jest running.

If you are ok with moving the entire project over to typescript I will give it another go, probably without babel. I'll have to do some reading.

**Comment by kosta** [comment]
I look into this in depth as soon as I have time time. From glancing at this, this looks good!

Is  `.babelrc` still needed?

**Comment by signed** [comment]
Lets put this one on hold and have a look at  #20. This has no babel at all and is completely migrated to typescript. Still room for improvement, but its a start.

**Pull request closed without merging**
