### PR TITLE
EventCard and EventConclusion

### PR DESCRIPTION
**Pull request by signed**

### CODE REVIEW

**Comment by kosta** [comment]
Very good structural change! I don't like the `EventConclusion` name too much. What about `EventInteraction` or similar?

**Comment by signed** [comment]
I think `EventInteraction` does not fit.

The manual speaks of 'completing city events'.
And bringing the event to its [conclusion](https://en.oxforddictionaries.com/definition/conclusion) is the responsibility of this component.

What about:
* `EventCompletion`
* `BringEventToConclusion`
* `EventResolver`
* `Storyteller`

**Comment by kosta** [comment]
Well it's the UI interactions to complete a city event... I don't like EventConclusion because at least when only first card is shown, the event is not at its conclusion.

Please go with `BringEventToConclusion` or `EventResolver`.

I love `Storyteller`, but it's the least informative name, in the sense that you know it will handle road and city events.

**Comment by signed** [comment]
Done

**Pull request merged**
