### PR TITLE
Improve battle goals

### PR DESCRIPTION
**Pull request by signed**
You can now choose between vanilla and community battle goals

### CODE REVIEW

**Comment by signed** [comment]
should be merged after #21

**Comment by kosta** [comment]
Wow, you're on fire!

I hope I can review soon...

**Comment by kosta** [comment]
Wow, that must have been a lot of work!

I think we need to improve the CSS of the "community" goals, so that they look more like cards. Maybe use the same background and the empty battle goal from Isaac Childres "[Files for creation](https://boardgamegeek.com/thread/1733586/files-creation)"?

**Comment by signed** [comment]
sounds good. Did you check with the author if we can use her texts in the tool?

**Comment by kosta** [comment]
Sent the email right now.

**Pull request merged**
